<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="audi" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot dimensions -->

  <!-- Physical Constant Macros -->
  <xacro:property name="M_PI" value="3.1415926535897931" />
  <!-- Dimension Macros -->
  <xacro:property name="carLength" value="0.3" />
  <xacro:property name="carWidth" value="0.15" />
  <xacro:property name="carHeight" value="0.1" />
  <xacro:property name="wheelRadius" value="0.06" />
  <xacro:property name="wheelWidth" value="0.025" />
 
  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find audi_description)/urdf/audi.gazebo" />
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find audi_description)/urdf/materials.xacro" />

  <!-- Used for fixing robot to Gazebo 'base_link' -->


  <!-- Base Link -->
  <link name="base_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="${carLength} ${carWidth} ${carHeight}" />
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="${carLength} ${carWidth} ${carHeight}" />
      </geometry>
      <material name="red"/>
    </visual>
    <inertial>
      <mass value="0.2" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.2" ixy="0.0" ixz="0.0" iyy="0.2" iyz="0.0" izz="0.2" />
    </inertial>
  </link>

  <joint name="front_joint" type="fixed">
    <parent link="base_link"/>
    <child link="front_link"/>
    <origin xyz="0.16 0.0 -0.1"/>
  </joint>

  <!-- Front link of Ackermann -->
  <link name="front_link">
    <collision>
      <geometry>
        <box size="${carLength*0.05} ${carWidth} ${carHeight*0.05}" />
      </geometry>
    </collision>
    <visual>
      <geometry>
        <box size="${carLength*0.05} ${carWidth} ${carHeight*0.05}" />
      </geometry>
      <material name="Aqua"/>
    </visual>
    <inertial>
      <mass value="0.01" />
      <origin xyz="0 0 0" />
      <inertia 
        ixx="0.01" ixy="0.0" ixz="0.0"
        iyy="0.01" iyz="0.0" 
        izz="0.01" />
    </inertial>
  </link>

  <!-- the left Ackermann bar -->
  <joint name="front_left_bar_joint" type="revolute" >
    <limit lower="-0.5" upper="0.5" effort="100" velocity="10" />
    <axis xyz="0 0 1" />
    <parent link="front_link" />
    <child link="front_left_bar_link" />
    <origin xyz="0.0 0.06 0.0" rpy="0 0 0" />
    <!--mimic joint="front_right_bar_joint" multiplier="1" /-->
  </joint>
  <link name="front_left_bar_link">
    <collision>
      <origin xyz="-0.02 0 0" />
      <geometry>
        <box size="${carLength*0.1} ${carWidth*0.133} ${carHeight*0.05}" />
      </geometry>
    </collision>
    <visual>
      <origin xyz="-0.02 0 0" />
      <geometry>
        <box size="${carLength*0.1} ${carWidth*0.133} ${carHeight*0.05}" />
      </geometry>
      <material name="green"/>
    </visual>
    <inertial>
      <mass value="0.01" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01" />
    </inertial>
  </link>

  <!-- the right Ackermann bar -->
  <joint name="front_right_bar_joint" type="revolute" >
    <limit lower="-0.5" upper="0.5" effort="100" velocity="10" />
    <axis xyz="0 0 1" />
    <parent link="front_link" />
    <child link="front_right_bar_link" />
    <origin xyz="0.0 -0.06 0.0" rpy="0 0 0" />
  </joint>

  <link name="front_right_bar_link">
    <collision>
      <origin xyz="-0.02 0 0" />
      <geometry>
        <box size="${carLength*0.1} ${carWidth*0.133} ${carHeight*0.05}" />
      </geometry>
    </collision>
    <visual>
      <origin xyz="-0.02 0 0" />
      <geometry>
        <box size="${carLength*0.1} ${carWidth*0.133} ${carHeight*0.05}" />
      </geometry>
      <material name="green"/>
    </visual>
    <inertial>
      <mass value="0.01" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01" />
    </inertial>
  </link>

  <!-- the front left wheel -->
  <joint name="front_left_wheel_joint" type="continuous" >
    <axis xyz="0 1 0" />
    <parent link="front_left_bar_link" />
    <child link="front_left_wheel_link" />
    <origin xyz="0 0.04 0" rpy="0 0 0" />
  </joint>

  <link name="front_left_wheel_link">
    <collision>
      <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
      <geometry>
        <cylinder radius="${wheelRadius}" length="${wheelWidth}" />
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
      <geometry>
        <cylinder radius="${wheelRadius}" length="${wheelWidth}" />
      </geometry>
      <material name="green"/>
    </visual>
    <inertial>
      <mass value="0.01" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01" />
    </inertial>
  </link>

  <!-- the front right wheel -->
  <joint name="front_right_wheel_joint" type="continuous" >
    <axis xyz="0 1 0" />
    <parent link="front_right_bar_link" />
    <child link="front_right_wheel_link" />
    <origin xyz="0 -0.04 0" rpy="0 0 0" />
  </joint>
  <link name="front_right_wheel_link">
    <collision>
      <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
      <geometry>
        <cylinder radius="${wheelRadius}" length="${wheelWidth}" />
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
      <geometry>
        <cylinder radius="${wheelRadius}" length="${wheelWidth}" />
      </geometry>
      <material name="green"/>
    </visual>
    <inertial>
      <mass value="0.01" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01" />
    </inertial>
  </link>


  <!-- a link aligned with the steer direction -->
  <joint name="steer_joint" type="revolute" >
    <limit lower="-0.5" upper="0.5" effort="100" velocity="10" />
    <axis xyz="0 0 1" />
    <parent link="front_link" />
    <child link="steer_link" />
    <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
  </joint>
  <link name="steer_link">
    <inertial>
      <mass value="0.01" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01" />
    </inertial>
    <visual>
      <origin xyz="-0.02 0 0" />
      <geometry>
      <box size="0.04 0.02 0.005" />
      </geometry>
      <material name="Red"/>
    </visual>
    <collision>
      <origin xyz="0.02 0 0" />
      <geometry>
      <box size="0.04 0.02 0.005" />
      </geometry>
    </collision>
  </link>

  <!-- the Ackerman bar -->
  <!-- Ackermann plugin -->
  <joint name="ackermann_joint" type="revolute" >
    <limit lower="-0.5" upper="0.5" effort="100" velocity="10" />
    <axis xyz="0 0 1" />
    <parent link="steer_link" />
    <child link="ackermann_bar_link" />
    <origin xyz="-0.04 0 0" rpy="0 0 0" />
  </joint>
  <!--joint name="ackermann_right_bar_joint" type="revolute" >
    <limit lower="-0.5" upper="0.5" effort="100" velocity="10" />
    <axis xyz="0 0 1" />
    <parent link="front_right_bar_link" />
    <child link="ackermann_bar_link" />
    <origin xyz="-0.04 0.06 0" rpy="0 0 0" />
  </joint-->

  <!--joint name="ackermann_left_bar_joint" type="revolute" >
    <limit lower="-0.5" upper="0.5" effort="100" velocity="10" />
    <axis xyz="0 0 1" />
    <parent link="ackermann_bar_link" />
    <child link="front_left_bar_link" />
    <origin xyz="-0.04 0.06 0" rpy="0 0 0" />
  </joint-->

  <link name="ackermann_bar_link">
    <inertial>
      <mass value="0.01" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01" />
    </inertial>
    <visual>
      <geometry>
        <box size="${carLength*0.05} ${carWidth} ${carHeight*0.1}" />
      </geometry>
    <material name="green"/>
    </visual>
    <collision>
      <geometry>
        <box size="${carLength*0.05} ${carWidth} ${carHeight*0.1}" />
      </geometry>
    </collision>
  </link>

  <!-- the back left wheel -->
  <joint name="back_left_wheel_joint" type="continuous" >
    <axis xyz="0 1 0" />
    <parent link="base_link" />
    <child link="back_left_wheel_link" />
    <origin xyz="-0.16 0.1 -0.1" rpy="0 0 0" />
  </joint>
  <link name="back_left_wheel_link">
    <inertial>
      <mass value="0.01" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
      <geometry>
        <cylinder radius="${wheelRadius}" length="${wheelWidth}" />
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
      <geometry>
        <cylinder radius="${wheelRadius}" length="${wheelWidth}" />
      </geometry>
    </collision>
  </link>
  <!-- the back right wheel -->
  <joint name="back_right_wheel_joint" type="continuous" >
    <axis xyz="0 1 0" />
    <parent link="base_link" />
    <child link="back_right_wheel_link" />
    <origin xyz="-0.16 -0.1 -0.1" rpy="0 0 0" />
  </joint>

  <link name="back_right_wheel_link">
    <inertial>
      <mass value="0.01" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
      <geometry>
        <cylinder radius="${wheelRadius}" length="${wheelWidth}" />
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
      <geometry>
        <cylinder radius="${wheelRadius}" length="${wheelWidth}" />
      </geometry>
      </collision>
  </link>

  <!-- laser plugin -->
  <joint name="laser_base_mount_joint" type="fixed">
    <origin xyz="0 0 0.05" rpy="0 0 0" />
    <parent link="base_link"/>
    <child link="laser_base_link"/>
  </joint>

  <link name="laser_base_link" type="fixed">
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0.0"/>
      <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
    </inertial>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0.025"/>
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0.025"/>
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
    </collision>
  </link>

  <joint name="base_scan_joint" type="fixed" >
    <origin xyz="0 0 0.05" rpy="0 0 0" />
    <parent link="laser_base_link" />
    <child link="base_scan_link"/>
  </joint>
  <link name="base_scan_link" type="laser">
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0.0"/>
      <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
    </inertial>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0.014"/>
      <geometry>
        <cylinder radius="0.0229" length="0.028"/>
      </geometry>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0.014"/>
      <geometry>
        <cylinder radius="0.0229" length="0.028"/>
      </geometry>
    </collision>
  </link>

   <!-- Adding loop joints -->
    <!-- Gazebo Ackermann loop joints -->
  <!--joint name="ackermann_left_bar_joint" type="revolute">
    <parent>ackermann_bar_link</parent>
    <child>front_left_bar_link</child>
    <axis>
      <xyz>0.000000 0.000000 1.000000</xyz>
      
      <dynamics/>
    </axis>
    <limit>
        <lower>-0.500000</lower>
        <upper>0.500000</upper>
        <effort>100.000000</effort>
        <velocity>10.000000</velocity>
      </limit>
  </joint>

  <joint name="ackermann_right_bar_joint" type="revolute">
    <parent>ackermann_bar_link</parent>
    <child>front_right_bar_link</child>
    <axis>
      <xyz>0.000000 0.000000 1.000000</xyz>
    
      <dynamics/>
    </axis>
      <limit>
        <lower>-0.500000</lower>
        <upper>0.500000</upper>
        <effort>100.000000</effort>
        <velocity>10.000000</velocity>
      </limit>
  </joint--> 

  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="steer_joint">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>



</robot>
